//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDGame
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogAcesso
    {
        public int IdLogAcesso { get; set; }
        public int UsuarioId { get; set; }
        public System.DateTime DataHoraAcesso { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
